imports:
    - { resource: parameters.yml }
    - { resource: services.yml }
    - { resource: security.yml }

framework:
    translator: { fallbacks: [ "en" ] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    templating:
        engines: ['twig']
    profiler:
        enabled: '%kernel.debug%'
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    cache: false
    form_themes:
             - bootstrap_3_layout.html.twig
           #  - foundation_5_layout.html.twig
    globals:
          # the value is the service's id
          global_content: '@AppBundle\Services\GlobalContent'
# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

knp_paginator:
    page_range: 5                       # number of links showed in the pagination menu (e.g: you have 10 pages, a page_range of 3, on the 5th page you'll see links to page 4, 5, 6)
    default_options:
        page_name: page                 # page query parameter name
        sort_field_name: sort           # sort field query parameter name
        sort_direction_name: direction  # sort direction query parameter name
        distinct: true                  # ensure distinct results, useful when ORM queries are using GROUP BY statements
        filter_field_name: filterField  # filter field query parameter name
        filter_value_name: filterValue  # filter value query paameter name
    template:
        pagination: '@KnpPaginator/Pagination/foundation_v5_pagination.html.twig'     # sliding pagination controls template
        sortable: '@KnpPaginator/Pagination/sortable_link.html.twig' # sort link template
        filtration: '@KnpPaginator/Pagination/filtration.html.twig'  # filters template

stof_doctrine_extensions:
    default_locale: en_US
    orm:
      default:
          sluggable: true
          timestampable: true
easy_admin:
    site_name: Webberdoo
    list:
        title: 'List of %%entity_label%%'
        actions:
           # - {name: edit, icon: pencil, label: Edit }
            - {name: delete, icon: trash, label: '' }
    entities:
        User:
           class: AppBundle\Entity\User
           label: Users
           list:
              actions:
                  - {name: edit, icon: pencil, label: Edit }
              fields:
                  - id
                  - email
                  - first_name
                  - last_name
                  - username
                  - { property: enabled, label: 'Enable?', type: boolean }
        Page:
           class: AppBundle\Entity\Page
           label: Pages
           list:
              actions:
                  - {name: edit, icon: pencil, label: Edit }
        Currency:
           class: AppBundle\Entity\Currency
           #controller: AppBundle\Controller\Admin\ImportController
           label: Currency
           list:
              actions:
                 - {name: -edit, icon: pencil, label: Import }
                 - {name: -new}
                 - {name: import_currency, type: route, label: Import, css_class: 'btn'  }
           disabled_actions: ['edit', 'new', 'delete']
           form:
              fields:
                 - { property: 'import_currency', type: 'entity', type_options: {class: 'AppBundle\Entity\Currency', choice_label: 'name'}}
                 #- { property: 'import_currency', type: 'choice', type_options: {choices: {'AUD':'AUD', 'BRL':'BRL', 'CAD':'CAD', 'CHF':'CHF', 'CLP':'CLP', 'CNY':'CNY', 'CZK':'CZK', 'DKK':'DKK', 'EUR':'EUR', 'GBP':'GBP', 'HKD':'HKD', 'HUF':'HUF', 'IDR':'IDR', 'ILS':'ILS', 'INR':'INR', 'JPY':'JPY', 'KRW':'KRW', 'MXN':'MXN', 'MYR':'MYR', 'NOK':'NOK', 'NZD':'NZD', 'PHP':'PHP', 'PKR':'PKR', 'PLN':'PLN', 'RUB':'RUB', 'SEK':'SEK', 'SGD':'SGD', 'THB':'THB', 'TRY':'TRY', 'TWD':'TWD', 'USD':'USD', 'ZAR':'ZAR'}} }
